eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true # This is also good practice for Docker/containerized environments

product:
  max: 10
  currency: $
